export default {
  // game action types
  NEXT_PHASE: "NEXT_PHASE",
  CHECK_END_GAME_CONDITIONS: "CHECK_END_GAME_CONDITIONS",
  SET_CARD_LIMIT_FLAG: "SET_CARD_LIMIT_FLAG",
  INCREASE_CARD_ID: "INCREASE_CARD_ID",

  // deck action types
  DRAW_CARD: "DRAW_CARD",
  DISCARD_CARD: "DISCARD_CARD",
  ATTACH_WEAPON: "ATTACH_WEAPON",
  SET_CARD_ATTACHED: "SET_CARD_ATTACHED",

  // player action types
  ADD_FOOD: "ADD_FOOD",
  CONSUME_FOOD: "CONSUME_FOOD",

  // people action types
  ADD_NEW_COMMON_PERSON: "ADD_NEW_COMMON_PERSON",
  ADD_NEW_PERSON: "ADD_NEW_PERSON"
};
