const deckData = [
  { name: "Wspaniały wojownik", type: "person", number: 2, value: 7 },
  { name: "Wódz", type: "person", number: 2, value: 6 },
  { name: "Duży człowiek", type: "person", number: 4, value: 5 },
  { name: "Wojownik", type: "person", number: 6, value: 4 },
  { name: "Łowca", type: "person", number: 8, value: 3 },
  { name: "Siłacz", type: "person", number: 4, value: 2 },

  { name: "Łowcy Mamutów", type: "food", number: 2, value: 6 },
  { name: "Nadmierna eksploatacja", type: "food", number: 2, value: 6 },
  { name: "Polowanie z siecią", type: "food", number: 2, value: 6 },
  { name: "Wielki łoś", type: "food", number: 2, value: 5 },
  { name: "Wielki dzik", type: "food", number: 2, value: 5 },
  { name: "Zabicie drapieznika", type: "food", number: 2, value: 5 },
  { name: "Żubry", type: "food", number: 2, value: 5 },
  { name: "Wyprawa myśliwska", type: "food", number: 2, value: 4 },
  { name: "Jeleń", type: "food", number: 2, value: 4 },
  { name: "Tereny łowieckie", type: "food", number: 2, value: 4 },
  { name: "Króliki", type: "food", number: 2, value: 3 },
  { name: "Ptaki", type: "food", number: 2, value: 3 },
  { name: "Gryzonie", type: "food", number: 2, value: 3 },
  { name: "Jaja", type: "food", number: 2, value: 3 },
  { name: "Łowienie ryb włócznią", type: "food", number: 2, value: 3 },
  { name: "Łowienie ryb siecią", type: "food", number: 2, value: 3 },
  { name: "Ustawienie pułapek", type: "food", number: 2, value: 3 },
  { name: "Ryba", type: "food", number: 2, value: 3 },
  { name: "Gady", type: "food", number: 2, value: 3 },
  { name: "Owady", type: "food", number: 2, value: 2 },
  { name: "Miód", type: "food", number: 2, value: 2 },
  { name: "Warzywa", type: "food", number: 2, value: 2 },
  { name: "Owoce", type: "food", number: 2, value: 2 },
  { name: "Owoc tykwy", type: "food", number: 2, value: 2 },
  { name: "Jagody", type: "food", number: 2, value: 2 },
  { name: "Dzikie ziarna", type: "food", number: 2, value: 2 },
  { name: "Orzechy i nasiona", type: "food", number: 2, value: 2 },
  { name: "Grzyby", type: "food", number: 2, value: 2 },
  { name: "Korzenie", type: "food", number: 2, value: 2 },
  { name: "Bulwy", type: "food", number: 2, value: 2 },
  { name: "Kora i liście", type: "food", number: 2, value: 1 }
];

export default deckData;
